# \u555F\u7528 dev (\u958B\u767C\u74B0\u5883) \u7684\u8A2D\u5B9A\u6A94
spring.profiles.active=dev

spring.datasource.url=jdbc:mariadb://localhost:3306/car_shop?characterEncoding=UTF-8
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Gmail \u5171\u7528\u8A2D\u5B9A
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true